# Generated by Django 4.2.6 on 2023-10-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_operador_logistico_user_is_pasajero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_operador_logistico",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_pasajero",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("operator", "Operator"), ("passenger", "Passenger")], default="passenger", max_length=10
            ),
        ),
    ]
